services:
  - type: web
    name: mysour
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SITE_URL
        sync: false
      - key: SITE_NAME
        sync: false 